-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf"
module('Advertisement_pb')


HPPLAYADRET = protobuf.Descriptor();
local HPPLAYADRET_ADSTATU_FIELD = protobuf.FieldDescriptor();
HPPLAYADMSG = protobuf.Descriptor();
local HPPLAYADMSG_PLAYSTATU_FIELD = protobuf.FieldDescriptor();

HPPLAYADRET_ADSTATU_FIELD.name = "adstatu"
HPPLAYADRET_ADSTATU_FIELD.full_name = ".HPPlayAdRet.adstatu"
HPPLAYADRET_ADSTATU_FIELD.number = 1
HPPLAYADRET_ADSTATU_FIELD.index = 0
HPPLAYADRET_ADSTATU_FIELD.label = 2
HPPLAYADRET_ADSTATU_FIELD.has_default_value = false
HPPLAYADRET_ADSTATU_FIELD.default_value = 0
HPPLAYADRET_ADSTATU_FIELD.type = 5
HPPLAYADRET_ADSTATU_FIELD.cpp_type = 1

HPPLAYADRET.name = "HPPlayAdRet"
HPPLAYADRET.full_name = ".HPPlayAdRet"
HPPLAYADRET.nested_types = {}
HPPLAYADRET.enum_types = {}
HPPLAYADRET.fields = {HPPLAYADRET_ADSTATU_FIELD}
HPPLAYADRET.is_extendable = false
HPPLAYADRET.extensions = {}
HPPLAYADMSG_PLAYSTATU_FIELD.name = "playstatu"
HPPLAYADMSG_PLAYSTATU_FIELD.full_name = ".HPPlayAdMsg.playstatu"
HPPLAYADMSG_PLAYSTATU_FIELD.number = 1
HPPLAYADMSG_PLAYSTATU_FIELD.index = 0
HPPLAYADMSG_PLAYSTATU_FIELD.label = 2
HPPLAYADMSG_PLAYSTATU_FIELD.has_default_value = false
HPPLAYADMSG_PLAYSTATU_FIELD.default_value = 0
HPPLAYADMSG_PLAYSTATU_FIELD.type = 5
HPPLAYADMSG_PLAYSTATU_FIELD.cpp_type = 1

HPPLAYADMSG.name = "HPPlayAdMsg"
HPPLAYADMSG.full_name = ".HPPlayAdMsg"
HPPLAYADMSG.nested_types = {}
HPPLAYADMSG.enum_types = {}
HPPLAYADMSG.fields = {HPPLAYADMSG_PLAYSTATU_FIELD}
HPPLAYADMSG.is_extendable = false
HPPLAYADMSG.extensions = {}

HPPlayAdMsg = protobuf.Message(HPPLAYADMSG)
HPPlayAdRet = protobuf.Message(HPPLAYADRET)

