-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf"
module('StarSoul_pb')


ACTIVESTARSOUL = protobuf.Descriptor();
local ACTIVESTARSOUL_ID_FIELD = protobuf.FieldDescriptor();
ACTIVESTARSOULRET = protobuf.Descriptor();
local ACTIVESTARSOULRET_ID_FIELD = protobuf.FieldDescriptor();
SYNCSTARSOUL = protobuf.Descriptor();
local SYNCSTARSOUL_GROUP_FIELD = protobuf.FieldDescriptor();
SYNCSTARSOULRET = protobuf.Descriptor();
local SYNCSTARSOULRET_ID_FIELD = protobuf.FieldDescriptor();

ACTIVESTARSOUL_ID_FIELD.name = "id"
ACTIVESTARSOUL_ID_FIELD.full_name = ".ActiveStarSoul.id"
ACTIVESTARSOUL_ID_FIELD.number = 1
ACTIVESTARSOUL_ID_FIELD.index = 0
ACTIVESTARSOUL_ID_FIELD.label = 2
ACTIVESTARSOUL_ID_FIELD.has_default_value = false
ACTIVESTARSOUL_ID_FIELD.default_value = 0
ACTIVESTARSOUL_ID_FIELD.type = 5
ACTIVESTARSOUL_ID_FIELD.cpp_type = 1

ACTIVESTARSOUL.name = "ActiveStarSoul"
ACTIVESTARSOUL.full_name = ".ActiveStarSoul"
ACTIVESTARSOUL.nested_types = {}
ACTIVESTARSOUL.enum_types = {}
ACTIVESTARSOUL.fields = {ACTIVESTARSOUL_ID_FIELD}
ACTIVESTARSOUL.is_extendable = false
ACTIVESTARSOUL.extensions = {}
ACTIVESTARSOULRET_ID_FIELD.name = "id"
ACTIVESTARSOULRET_ID_FIELD.full_name = ".ActiveStarSoulRet.id"
ACTIVESTARSOULRET_ID_FIELD.number = 1
ACTIVESTARSOULRET_ID_FIELD.index = 0
ACTIVESTARSOULRET_ID_FIELD.label = 2
ACTIVESTARSOULRET_ID_FIELD.has_default_value = false
ACTIVESTARSOULRET_ID_FIELD.default_value = 0
ACTIVESTARSOULRET_ID_FIELD.type = 5
ACTIVESTARSOULRET_ID_FIELD.cpp_type = 1

ACTIVESTARSOULRET.name = "ActiveStarSoulRet"
ACTIVESTARSOULRET.full_name = ".ActiveStarSoulRet"
ACTIVESTARSOULRET.nested_types = {}
ACTIVESTARSOULRET.enum_types = {}
ACTIVESTARSOULRET.fields = {ACTIVESTARSOULRET_ID_FIELD}
ACTIVESTARSOULRET.is_extendable = false
ACTIVESTARSOULRET.extensions = {}
SYNCSTARSOUL_GROUP_FIELD.name = "group"
SYNCSTARSOUL_GROUP_FIELD.full_name = ".SyncStarSoul.group"
SYNCSTARSOUL_GROUP_FIELD.number = 1
SYNCSTARSOUL_GROUP_FIELD.index = 0
SYNCSTARSOUL_GROUP_FIELD.label = 2
SYNCSTARSOUL_GROUP_FIELD.has_default_value = false
SYNCSTARSOUL_GROUP_FIELD.default_value = 0
SYNCSTARSOUL_GROUP_FIELD.type = 5
SYNCSTARSOUL_GROUP_FIELD.cpp_type = 1

SYNCSTARSOUL.name = "SyncStarSoul"
SYNCSTARSOUL.full_name = ".SyncStarSoul"
SYNCSTARSOUL.nested_types = {}
SYNCSTARSOUL.enum_types = {}
SYNCSTARSOUL.fields = {SYNCSTARSOUL_GROUP_FIELD}
SYNCSTARSOUL.is_extendable = false
SYNCSTARSOUL.extensions = {}
SYNCSTARSOULRET_ID_FIELD.name = "id"
SYNCSTARSOULRET_ID_FIELD.full_name = ".SyncStarSoulRet.id"
SYNCSTARSOULRET_ID_FIELD.number = 1
SYNCSTARSOULRET_ID_FIELD.index = 0
SYNCSTARSOULRET_ID_FIELD.label = 2
SYNCSTARSOULRET_ID_FIELD.has_default_value = false
SYNCSTARSOULRET_ID_FIELD.default_value = 0
SYNCSTARSOULRET_ID_FIELD.type = 5
SYNCSTARSOULRET_ID_FIELD.cpp_type = 1

SYNCSTARSOULRET.name = "SyncStarSoulRet"
SYNCSTARSOULRET.full_name = ".SyncStarSoulRet"
SYNCSTARSOULRET.nested_types = {}
SYNCSTARSOULRET.enum_types = {}
SYNCSTARSOULRET.fields = {SYNCSTARSOULRET_ID_FIELD}
SYNCSTARSOULRET.is_extendable = false
SYNCSTARSOULRET.extensions = {}

ActiveStarSoul = protobuf.Message(ACTIVESTARSOUL)
ActiveStarSoulRet = protobuf.Message(ACTIVESTARSOULRET)
SyncStarSoul = protobuf.Message(SYNCSTARSOUL)
SyncStarSoulRet = protobuf.Message(SYNCSTARSOULRET)

